### ISSUE TITLE
publishing

### ISSUE THREAD

**Issue by echo66** [ivansglazunov/meteor-trees#2]
Greetings!

Does this package manages what documents will be published, based on the links? For example, in https://github.com/englue/meteor-publish-composite/ you would use the 'find' and 'children' fields to choose what relations will be published.

**Comment by ivansglazunov** [comment]
This package deals with link and inheritance links. Here old version of the package. New version is here: [shuttler:graphs](https://github.com/meteor-shuttler/graphs). Inheritance is implemented by a separate package with the ability to configure each inheritance instance from the database, soon.

[ivansglazunov:shuttle-fetching](https://github.com/ivansglazunov/meteor-shuttle-fetching) with dependence to [ivansglazunov:shuttle-rights](https://github.com/ivansglazunov/meteor-shuttle-rights) solves `find` problem another way. It allows with a single query to receive the cursor only with the approval documents. Precalculate permissions for each user or group of users.

However, this is the same old version. New in the next 5 days will be published in the organization of `meteor-shuttle`. In the old version of the request wrapper occurs with `collection-hooks``colelction.before.find`. Because of this, the server can not be fetch hidden documents. In the new it will be done in the `publish`, and offered for manual use.

There will soon be an interface for debug graphs on [cytoscape](http://js.cytoscape.org/)

My English is poor. Google translator helps me).

**Comment by ivansglazunov** [comment]
The new version really convenient and completely solved the problem you described.
Only users with the rights to receive documents and their links.

Or you can on the basis of [ivansglazunov:shuttle-fetching](https://github.com/ivansglazunov/meteor-shuttle-fetching) to write your own version and use it in the `publish`.

**Comment by echo66** [comment]
Thanks for the clarification, @ivansglazunov :+1: :+1: 

By the way, are all edges unnamed? I'm asking this because in both https://github.com/meteor-shuttler/graphs and https://github.com/ivansglazunov/meteor-trees , there are no edge labels, AFAIK. If there are no edge labels, that means you need to create a collection for each edge label. That would be fine but only if you use autosubscribe and insecure packages.

**Comment by ivansglazunov** [comment]
There are no restrictions on the links custom fields. They only need to attach in [SimpleSchema](https://github.com/aldeed/meteor-simple-schema).

Example:

``` js
col.attachSchema(new SimpleSchema({
    myField: {
        type: String
    }
}));
```

In [shuttler:graphs](https://github.com/meteor-shuttler/graphs) you can:

``` js
col.insert.link(doc1, doc2, { myField: '123' }) // id: String
```

Similar works `find`.

**Comment by echo66** [comment]
ooooooooooooooooooooooooooohhhhh now I understand the 'query' parameter. So, when I'm retrieving documents through 'find.link' methods, the 'query' parameter works like a filter and, in 'insert.link', it provides the custom fields. Is that right?

**Comment by ivansglazunov** [comment]
Yes.
Maybe rename the argument `query` to `customFields` in `insert.link`?

**Comment by echo66** [comment]
Well, that would make the difference completely clear, AFAIK. :+1: 

So, with your library, we can implement a semantic system for the properties.

**Comment by ivansglazunov** [comment]
Thank you. I am glad to be useful)

In my private repository is almost complete system of access rights and visibility, and to any other such rights. It is planned to publish in the coming days. This allows you to do complex tree of rights imposed on some graphs-trees. Managed and from the server and from the database. We can check out my coding direction.

It will be like [ivansglazunov:shuttle-rights](https://github.com/ivansglazunov/meteor-shuttle-rights), but the inheritance will be smarter and will be limited to the rights to `publish` level.

It would be helpful? Or properties do not require the rights?

**Comment by echo66** [comment]
I would like to answer but I'm kind of confused with the descriptions you wrote in https://github.com/ivansglazunov/meteor-shuttle-rights

**Comment by ivansglazunov** [comment]
This is the first "draft" version of documentation. I agree he did not complete.

The bold lines - by the user.
Thin line - controlled (created and deleted) system `inherit` automatically.

Much has changed in the `shuttler`.

Many individual repositories instead of one (rights) + fetching ...
- `selectorOfLinksDistribution`
- `preCalculatingToDocuments`
- `permissions` as base methods and helpers
- `publish` - helpers for publishing

In addition, instead of just "permission" to fetch or own, will be dual permissions:
- `used` `unused`
- `own.allow` `own.deny`
- `fetch.allow` `fetch.deny`
- `update.allow` `update.deny`
- `remove.allow` `remove.deny`

Probably it is necessary to understand how `inherit` works now (in the future it will be more flexible). What do most of the work is carried out as a response to events on server and restructuring links inherited from user-created links. If you want I'll show nice demos too)

The new implementation inherit [select](https://github.com/meteor-shuttler/select) (almost ready) so much more flexibility:
- Not only insert and remove watching, but also to update source and target fields watching.
- Not only target => source inheritance but in any direction.
- Not only the ends (source-target) of the links but also and to link-documents too.
- Not only server rules, but also in db rules.

For you to understand what is intended `inherit` in the tree?
It can be understood as:
It inherits the tree itself to some of the documents on other trees.
Or extends a link through its "duplicate" on some of the documents on other trees.
Or link is a selector to many documents in many trees.

You can try to say a controversial statement, as it was understood from the documentation.
You can refer to the documentation saying what is missing, and I added it.
You can write on skype (my nickname), and make it more interactive. I'll show nice demos)
You can pose the problem and not to ponder :) I'll write as I see the solution.
You can wait. The next version is already in the "shuttler". Many items will be more.

**Comment by echo66** [comment]
Well, you were the one who talked about inheritance so you should answer that. :P

When you talk about inheritance, in meteor-graph and meteor-tree contexts, do you mean the usual "sub class of", similar to description logics (i.e.: look at OWL inheritance)? 

I will add you later this day to skype. Right now, I'm working.

**Comment by ivansglazunov** [comment]
We can talk here: [Gitter Shuttler room](https://gitter.im/meteor-shuttler/graphs?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

**Comment by ivansglazunov** [comment]
One tree/graph - as one property.
You can understand tree as a hierarchical structure, or as assignment to the hierarchical structure of some property (tree/graph).
One (tree/graph) can be a structure as [used](https://github.com/ivansglazunov/meteor-shuttle-rights#used). For example, it is nesting for some posts documents.
Other trees, such as [owning](https://github.com/ivansglazunov/meteor-shuttle-rights#owning), a property. Some user (target) owns part of the document tree (by source).
The owning right given to 1 (user) and automatically inherited to 2, 3, 4 and 5.
Only first link can be changed by user. Other links works fully automatically.

**Comment by ivansglazunov** [comment]
If you add mark (_owned: [String]) to the documents (on .after.link/.after.unlink), it can be used in queries.
